### ISSUE TITLE
How to include urls to redirect

### ISSUE THREAD

**Issue by bnbabu55** [GatsbyCentral/gatsby-plugin-htaccess-redirects#9]
I installed this plugin and included it in the gatsby.config.js file as noted in the instruction. 
`{
  resolve: `gatsby-plugin-htaccess-redirects`,
  options: {
    prefix: "<IfModule mod_rewrite.c>\nRewriteEngine On",
    suffix: "</IfModule>",
  },
},`
Then ran gastby build, now the output .htaccess file is just a shell having the following content.
`<IfModule mod_rewrite.c>
RewriteEngine On

</IfModule>`

I don't know how to include the urls to be redirected. Where do we specify that, documentation is not clear about this.

**Comment by chmac** [comment]
Redirects are created in Gatsby, they're only rendered out by this plugin, so they're not covered in our docs.

**Comment by rajanmagar** [comment]
@chmac Generating only .htaccess file doesn't make sense any one create that file without plugin.
